[package]
name = "restrict"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
bytesize = "1.1.0"
cgroups-rs = { git = "https://github.com/kata-containers/cgroups-rs" }
shell-words = "1.0"
colored = "2.0"
scopeguard = "1.2.0"
