[package]
name = "restrict"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
parse-size = "1.0.0"
cgroups-rs = { git = "https://github.com/kata-containers/cgroups-rs" }
